w4d5/NinetyNineCats/config/routes.rb
NinetyNineCats::Application.routes.draw do
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:create, :new] do
    post "approve", on: :member
    post "deny", on: :member
  end
  resource :session, only: [:create, :destroy, :new]
  resources :users, only: [:create, :new]

  root to: redirect("/cats")
end

w4d5/NinetyNineCats/app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password

  has_many :cats

  after_initialize :ensure_session_token

  validates :password_digest, presence: true
  # If a password was set, we validate it meets the requirements.
  # Note the `allow_nil`.
  validates(
    :password,
    length: { minimum: 6, allow_nil: true }
  )
  validates :session_token, presence: true, uniqueness: true
  validates :username, presence: true, uniqueness: true

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)

    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def owns_cat?(cat)
    cat.user_id == self.id
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end
end

w4d5/NinetyNineCats/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_no_user!

  def create
    @user = User.new(user_params)
    if @user.save
      login_user!(@user)

      msg = UserMailer.welcome_email(@user)
      msg.deliver

      redirect_to @url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def new
    @user = User.new
    render :new
  end

  private
  def user_params
    params.require(:user).permit(:password, :username)
  end
end

w4d5/NinetyNineCats/app/views/users/new.html.erb
<h1>New User</h1>

<%= render "shared/errors" %>

<form action="<%= users_url %>" method="post">
  <%= auth_token %>

  <label for="user_username">User Name</label>
  <input type="text"
         name="user[username]"
         id="user_username"
         value="<%= @user.username %>">
  <br>

  <label for="user_password">Password</label>
  <input type="password"
         name="user[password]"
         id="user_password"
         value="<%= @user.password %>">
  <br>

  <input type="submit">
</form>

<% content_for :footer do %>
  This is where you create an account.
<% end %>